title: "Kind of Blue"
url: "http://kindofblue.com"
author: "Bill Turner"
email: "hello@billturner.me"
description: "The weblog of Pittsburgh-based Ruby on Rails developer Bill Turner."
timezone: "America/New_York"
lsi: false

source: .
paginate: 10
permalink: /:year/:month/:title

markdown: redcarpet
pygments: false

exclude: ["nginx.conf", "README.markdown", "_plugins", "_assets", "_drafts", "Gemfile", "Gemfile.lock", ".ruby-version", ".gitignore"]

pinboard_tag:
  user:  "billturner"
  limit: 10
  tags:  "inspiration"
  list_tag: "ul"
  show_desc: true

# assets
assets:
  dirname: "assets"
  compress:
    css: "sass"
    js: "uglifier"
  sources:
  - "_assets/javascripts"
  - "_assets/stylesheets"
  - "_assets/images"
