title: "Brilliant Corners"
url: "http://brilliantcorners.org"
author: "Bill Turner"
email: "billturner@gmail.com"
description: "The weblog of Pittsburgh-based Ruby on Rails developer Bill Turner"

auto: false
source: .
paginate: 10
permalink: /:year/:month/:title

markdown: rdiscount
pygments: false

exclude: ["nginx.conf", "README.markdown", "_drafts", "Gemfile", "Gemfile.lock", ".rvmrc", ".gitignore"]
