title: "Brilliant Corners"
url: "http://brilliantcorners.org"
author: "Bill Turner"
email: "hello@billturner.me"
description: "The weblog of Pittsburgh-based Ruby on Rails developer Bill Turner."

source: .
paginate: 10
permalink: /:year/:month/:title

markdown: redcarpet
pygments: false

exclude: ["nginx.conf", "README.markdown", "_plugins", "_assets", "_drafts", "Gemfile", "Gemfile.lock", ".ruby-version", ".rvmrc", ".gitignore"]

# assets
assets:
  dirname: "assets"
  compress:
    css: "sass"
    js: "uglifier"
  sources:
  - "_assets/javascripts"
  - "_assets/stylesheets"
  - "_assets/images"
